// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxeb_koWasK-cvnlf1lkvF09zw3tzOZgg',
    appId: '1:184682599913:web:3938ed74dcbd1580d0e778',
    messagingSenderId: '184682599913',
    projectId: 'smart-office-392ba',
    authDomain: 'smart-office-392ba.firebaseapp.com',
    databaseURL: 'https://smart-office-392ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-office-392ba.appspot.com',
    measurementId: 'G-DPGTWHM9FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5VTQVIkMMuyI6fMEGY5xZq-_UGorZjoc',
    appId: '1:184682599913:android:11c08e5cb3b148a2d0e778',
    messagingSenderId: '184682599913',
    projectId: 'smart-office-392ba',
    databaseURL: 'https://smart-office-392ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-office-392ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9rSnNHCDV4T_UgPUOM2zwlhXrouHcpmg',
    appId: '1:184682599913:ios:f5643c3fe560ca99d0e778',
    messagingSenderId: '184682599913',
    projectId: 'smart-office-392ba',
    databaseURL: 'https://smart-office-392ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-office-392ba.appspot.com',
    iosClientId: '184682599913-tuv7sr143v8vsuc6pgeiblprhnreern8.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9rSnNHCDV4T_UgPUOM2zwlhXrouHcpmg',
    appId: '1:184682599913:ios:718f224596384e19d0e778',
    messagingSenderId: '184682599913',
    projectId: 'smart-office-392ba',
    databaseURL: 'https://smart-office-392ba-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-office-392ba.appspot.com',
    iosClientId: '184682599913-o48oa3sf6blgknoofoqgknll9v4l1ak5.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartOffice.RunnerTests',
  );
}
